This Jenkinsfile for trivy

diff --git a/ci/Jenkinsfile b/ci/Jenkinsfile
--- a/ci/Jenkinsfile
+++ b/ci/Jenkinsfile
@@ -46,7 +46,20 @@ pipeline {
         }
       }
     }
-
+   stage('Image scan') {
+     when {
+       expression { return env.IMAGE_NAME != null }
+    }
+    steps {
+      sh '''
+        echo "Scanning image with Trivy..."
+        trivy image --severity HIGH,CRITICAL --exit-code 1 $IMAGE_NAME:$IMAGE_TAG || {
+          echo "High/Critical vulnerabilities found, failing build."
+          exit 1
+       }
+     '''
+    }
+  }
     // 3) Deploy to dev using Helm
     stage('Helm Upgrade (dev)') {
       steps {
